### ISSUE TITLE
Application shows as deployed but all I get in the browser is a blank page

### ISSUE THREAD

**Issue by craneoteca** [ine-labs/GCPGoat#10]
Hi, I am new to GCP and would appreciate some help. I went through the gcpgoat install steps (had to enable several APIs along the way) and was able to deploy the application. The terraform apply shows:
Apply complete! Resources: 20 added, 0 changed, 3 destroyed.
Outputs:
ad_Target_URL = "https://us-west1-gcp-goat-XXXXXXXXXXXXXXXXXXXXXXXXXXXX"

However, when I navigate to the URL, all I see is am empty page such as the one below. Any ideas on what could be missing?

![image](https://github.com/ine-labs/GCPGoat/assets/12161207/d6f57348-f230-4d89-bf21-318aeb89bc62)

I tried creating a new project and re-deploying but got the same blank page. 

Thanks!

**Comment by munirohitrishi** [comment]
@craneoteca Yes facing the same issue, even the resources are not created on gcp console
@za

**Comment by za** [comment]
Hi @munirohitrishi @craneoteca make sure you have access to billing.

BTW, have you guys run `terraform init`?

**Comment by munirohitrishi** [comment]
Hey hi, @za yes we have full access to the billing and we have run `terraform init` as well

**Comment by za** [comment]
Hi @munirohitrishi can you paste result of these commands?

```
$ terraform init
$ terraform apply --auto-approve
```

**Comment by munirohitrishi** [comment]
yes @za I got like this


No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

ad_Target_URL = "https://us-west1-gcp-goat-xxxxxxxxxxxx.cloudfunctions.net/blogapp-xxxxxxxxxx"

**Comment by sherinsteph** [comment]
Hey @craneoteca @munirohitrishi , I recommend trying a fresh installation from scratch. Reapplying might cause some features deployed in Firestore to stop working, leading to a blank page. Trying a fresh installation could help fix the blank page issue you are experiencing.

We've tried reproducing the issue, but the application seems to be working fine during deployment on our end. However, if the problem persists, feel free to let us know.

**Comment by za** [comment]
Hi @craneoteca / @munirohitrishi , maybe you can also try to run this first:

```
$ terraform destroy
```

then repeat the deployment steps.
