### ISSUE TITLE
Something wrong in the backend server

### ISSUE THREAD

**Issue by D-Virus** [ine-labs/GCPGoat#11]
I deployed all the services without erros, but when I try to login or create new accounts I got the following error message:

There is something wrong in the backend server

![image](https://github.com/ine-labs/GCPGoat/assets/1059824/4f8cb7aa-70ba-4a05-a4d6-1c9330a9d8ed)

**Comment by za** [comment]
Hi @D-Virus you need to sign up first, before login. Can you try to sign up?

BTW, the error message is triggered somewhere here: https://github.com/search?q=repo%3Aine-labs%2FGCPGoat%20something%20wrong&type=code

**Comment by za** [comment]
Hi @nishantsharmax maybe we can improve the ERROR message, as currently it's too general. Although, if it's triggered by login, the error was triggered here: https://github.com/ine-labs/GCPGoat/blob/21f4ad4ed51d0d11e0a6e028a94710e0e2005b15/modules/module-1/src/src/sections/auth/login/LoginForm.js#L85 CMIIW.

**Comment by bobdolectf** [comment]
> Hi @D-Virus you need to sign up first, before login. Can you try to sign up?
> 
> BTW, the error message is triggered somewhere here: https://github.com/search?q=repo%3Aine-labs%2FGCPGoat%20something%20wrong&type=code

I'm getting the same output when trying to sign up.

**Comment by za** [comment]
Hi @D-Virus do you still having this issue? 

I just deployed GCPGoat, and I didn't have any issue:
* sign up :heavy_check_mark: 
* login :heavy_check_mark: 

Maybe we can close this issue if you no longer experiencing this.

**Comment by bobdolectf** [comment]
> Hi @D-Virus do you still having this issue?
> 
> I just deployed GCPGoat, and I didn't have any issue:
> 
> * sign up ✔️
> * login ✔️
> 
> Maybe we can close this issue if you no longer experiencing this.

I'm seeing the same issue on my end after deployment with no errors.
