### ISSUE TITLE
Getting error could not find image or family ubuntu-os-cloud/ubuntu-1804-lts

### ISSUE THREAD

**Issue by munirohitrishi** [ine-labs/GCPGoat#12]
@za I have run the Terraform getting errors like  could not find image or family ubuntu-os-cloud/ubuntu-1804-lts 
The reason for this error is recently gcp has deprecated the ubuntu-1804-lts `https://cloud.google.com/compute/docs/eol/ubuntu-eol`
![image](https://github.com/ine-labs/GCPGoat/assets/55479641/dce682d4-df5a-4e7a-b29c-ac94361513c5)

**Comment by za** [comment]
@munirohitrishi Can you try from this branch? https://github.com/ine-labs/GCPGoat/pull/13

**Comment by za** [comment]
We can close/resolve this issue now @munirohitrishi as the PR has been merged.
