### ISSUE TITLE
how to solve this issue

### ISSUE THREAD

**Issue by varsaw123** [ine-labs/GCPGoat#14]
![Screenshot 2023-08-01 113837](https://github.com/ine-labs/GCPGoat/assets/117669600/fa571432-250e-4aeb-983f-4b807fabd7c3)

**Comment by sherinsteph** [comment]
@varsaw123 It looks like there's a permissions issue with Terraform. The error suggests that Terraform doesn't have the right permissions to create or modify files in the folder where it saves the state. To fix this, make sure the user running Terraform has read and write permissions for that folder.

If you're still having trouble with local permissions, you can try deploying the application using GCP Cloud Shell. It's an alternative method that may help you avoid these permission conflicts and proceed with the deployment smoothly.

**Comment by varsaw123** [comment]
Thank you
