### ISSUE TITLE
Invalid Authorization while trying SSRF attack

### ISSUE THREAD

**Issue by BarakAgranov** [ine-labs/GCPGoat#18]
while trying the first objective, on step 3, no URL comes back as response, but "{"body": "Invalid Authorization"}" appears

**Comment by sherinsteph** [comment]
@BarakAgranov, we updated the code for the JWT token because GCP Cloud Functions Gen 1 no longer accepts header keys with underscores. It's working well now. Thanks for bringing this to our attention!
